### PR TITLE
Old Apple Page Clone

### PR DESCRIPTION
**Pull request by ElijahTobs**
**Apple Clone**

- add navbar
- add background images
- add footer

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @ElijahTobs 
### You have a good job :clap: However, you have a few fixes to make before the project could be approved.
- Remove the commented lines in your html and css files
remove uncommented fles
- Validate your html file by running it through w3 validator, use [this link](https://validator.w3.org/#validate_by_upload)
validator
- Your content should go full width, refer the original website
content full width
### Make these changes and resubmit for another code review. Good luck.
-For more clarification contact me on slack @iamraymond
- Happy coding!

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi @ElijahTobs 👋

You've done quite will on this project.👏

However, there are changes to be met before proceeding.

- [ ] Required - Please do fix your linting issues as some checks are failing. We need to get this mark(❌)  beside your commit message to change to this mark(✅).

- [ ] Required - Kindly adjust the width of your navbar as it looks more wider than the original.
This is yours👇
ice_screenshot_20200408-092829

- [ ] Required - Also on your navbar, you need to add a hover effect as seen in the original page, a change in background-color occurs on hover.

- [ ] Required - Kindly ensure you fix the width of the four elements at the bottom of the page, as they seem to be overflowing the container.[Screenshot]👇
ice_screenshot_20200408-092734

- [ ] Required - Also the footer elements are seen to be towards the edge of the page, but the original has the footer elements more at the center of the page.
**THIS IS YOURS**👇
ice_screenshot_20200408-092756

**THIS IS THE WAY IT SHOULD BE👇**
ice_screenshot_20200408-093018

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by ElijahTobs** [comment]
Yoooooooooooooooooooooooooooooooooooy!

I successfully overcame stickler.

**Comment by lekegitrepo** [comment]
### Hi @ElijahTobs 👏 💯 
### You did a good job. This project is approved ⭐️ 

### Optional:
**_- Try to fix the page it has a horizontal scroll bar._**

### Reviewed by _Temitayo Adeleke._

-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/temitayo-adeleke/)

**Review by lekegitrepo — APPROVED** [review]
### Status: Approved

**Pull request merged**
